package org.tolley.wlg.vehicle;

import java.util.ArrayList;
import java.util.List;

public abstract class VehicleParser {
    //List of the Vehicle objects
    protected ArrayList<Vehicle> vehiclesList;
    //lines of parsed Vehicles
    protected List<String[]> csvFileLines;

    /**
     * Parses the Vehicle input
     * @return an ArrayList of all parsed Vehicles
     */
    public abstract ArrayList<Vehicle> parseVehicles();

    /**
     * Retrieves the ArrayList of Vehicles which have been generated by the parser
     * @return the list of Vehicles
     */
    public ArrayList<Vehicle> getVehiclesArrayList() {
        return vehiclesList;
    }

    /**
     * Processes each line which has been parsed
     * Converts the lines into Vehicle objects
     */
    protected void processVehicles(){
        /**
         * csvLine Array position mapping:
         * 0: firstName
         * 1: lastName
         * 2: email
         * 3: vehicleType
         * 4: vehicleName
         * 5: vehicleLength
         */
        vehiclesList = new ArrayList<>();
        for(String[] line: csvFileLines){
            String firstName = line[0];
            String lastName = line[1];
            String email = line[2];
            String vehicleType = line[3];
            String vehicleName = line[4];
            String vehicleLength = line[5];

            Vehicle vehicle = new Vehicle(firstName, lastName, email, vehicleType, vehicleName, vehicleLength);
            vehiclesList.add(vehicle);
        }
    }
}